### ISSUE TITLE
boost threading compilation errror

### ISSUE THREAD

**Issue by srikanthmalla** [RMonica/rviz_cloud_annotation#1]
Hi, when compiling I am getting this errror

error "Threading support unavaliable: it has been explicitly disabled with BOOST_DISABLE_THREADS"

Even after explicitly adding cxxflags like this in cmake, I get this error
set(CMAKE_CXX_FLAGS "-std=c++11 -pthread -lboost_thread")

**Comment by RMonica** [comment]
Hi.

From a quick research, this seems to be tied to a specific, quite old Boost version (1.48).
What ROS version are you using?
What compiler?
What Boost version?
What Ubuntu version?

Also, you shouldn't be able to use ROS at all without multithreading support.
Is your ROS installation working? Can you compile other packages?

**Comment by RMonica** [comment]
No answer. Closed.
