### ISSUE TITLE
annotating the own VLP16 data

### ISSUE THREAD

**Issue by nesakeerthi** [RMonica/rviz_cloud_annotation#10]
@RMonica  thanks for greak work and sharing.

Is it possible to annotate the point clouds which are captured using the VLP-16 Velodyne sensor?
Right now i do have the data collected as raw .pcap files and preprocessed using the matlab.I need to annotate the same.

1. rviz_cloud annotation will support the which kind of file format .pcd or .bin??

pls help

**Comment by RMonica** [comment]
This tool supports only the PCD format, from the Point Cloud Library.

It might be possible to annotate a point cloud from a Velodyne. However:
- control points may not work very well: the annotation tool expects an approximately constant point density. However, Velodyne point clouds have points very close to each other within the same channel, and far from each other between different channels
- I don't think the Velodyne sensor provides point normals. You might try setting `normal_importance` to `0`, in that case.
