### ISSUE TITLE
could not open file example.ann

### ISSUE THREAD

**Issue by weisongwen** [RMonica/rviz_cloud_annotation#2]
Hi @RMonica , thanks for your work on this package.
when I launch the example.launch file, the error is obtained as follwoing:

[ERROR] [1533157457.290403366]: rviz_cloud_annotation: could not open file: /home/wenws/rviz_cloud_annotation/src/rviz_cloud_annotation/rviz_cloud_annotation/data/example.ann

**Comment by RMonica** [comment]
Hi @weisongwen,
the example.ann file is created when you annotate the point cloud and then save the annotation.
The error is expected if there is not an annotation for the point cloud yet.
The node just loads the default (i.e.: empty annotation).

I now notice that the provided example.launch file overrides the original point cloud with the annotated one. This can be confusing. Fixed.

**Comment by weisongwen** [comment]
hi @RMonica ,
thanks for your kind information,
best
welson,

**Comment by weisongwen** [comment]
Hi, @RMonica 
I still got this error
```
[ERROR] [1533157457.290403366]: rviz_cloud_annotation: could not open file: /home/wenws/rviz_cloud_annotation/src/rviz_cloud_annotation/rviz_cloud_annotation/data/example.ann
```
It seems that i do not have the example.ann file. Do you have any ideas on this issue? Thanks a lot,

best,
welson

**Comment by RMonica** [comment]
The `example.ann` file is created when you save the annotation (using the File menu in the lower left panel) for the first time. It contains the current annotation.
If you don't have an annotation for your point cloud yet (e.g. when you just downloaded the example from the repository), that error is expected.

**Comment by weisongwen** [comment]
@RMonica , thanks for your kind reply,
I do not have the ```example.ann``` as I directly download the package from your github. After I run the launch file, the node died directly as the node cannot find the ```example.ann```. Do you have any suggestions to solve this issue? Or could you provide a example.ann file?

Best,
Welson

**Comment by RMonica** [comment]
Ok, now I understand your issue. The node crashes right after that error.
However, the node should be able to start even if the `example.ann` file is missing, so it may or may not be the cause of the issue.
Can you post the console log up to the actual crash, i.e. the line with "The process has died!" or similar?

I'm also attaching an `example.ann` file for you to try.
[example.ann.zip](https://github.com/RMonica/rviz_cloud_annotation/files/2662092/example.ann.zip)

Cheers,
RMonica

**Comment by weisongwen** [comment]
@RMonica , thanks! The error comes from the version of ROS. This error do not come in ROS kinetic. previously, ROS jade!
Best,
Welson,
