### ISSUE TITLE
how to save labeled pointcloud?

### ISSUE THREAD

**Issue by jeannotes** [RMonica/rviz_cloud_annotation#4]
Hi, really thank you for your amazing work, but can I save corresponding labeled pointcloud?

**Comment by RMonica** [comment]
Hi.

In the lower-left panel, open the File menu and select Save.
The file name is set by ROS parameters `annotation_write_filename`, `annotation_cloud` and `label_names_filename` (see README). Current values of the parameters are also written to the terminal when you save.
