### ISSUE TITLE
[ERROR] [1543929914.993192563]:  [ERROR] [1543930033.527196394]  [1543930033.561831781]: PluginlibFactory

### ISSUE THREAD

**Issue by ldepn** [RMonica/rviz_cloud_annotation#5]
when I launch the example.launch file, the error is obtained as follwoing:
[ERROR] [1543929914.993192563]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation Tool' failed to load.  Error: Failed to load library /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so))
[ERROR] [1543929915.026094747]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation' failed to load.  Error: Failed to load library /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so))
[ERROR] [1543930033.527196394]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation Tool' failed to load.  Error: Failed to load library /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so))
[ERROR] [1543930033.561831781]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation' failed to load.  Error: Failed to load library /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/jnu/catkin_ws/devel/lib//librviz_cloud_annotation_plugin.so))

**Comment by RMonica** [comment]
Please report also:
- ROS version
- Operating system version

It seems that the package was linked against a library that does not exist in your system.
Did you try cleaning the package and recompiling?

**Comment by ldepn** [comment]
This error has been resolved， this is the Qt version problem.

**Comment by RMonica** [comment]
Ok...
