### ISSUE TITLE
No pointcloud visualised when running the example

### ISSUE THREAD

**Issue by Marcel-Gabriel-bertrandt** [RMonica/rviz_cloud_annotation#8]
I successfully installed the required libraries and this package.

However, when I start this annotation tool via "roslaunch rviz_cloud_annotation example.launch", rviz starts but there is no pointcloud at all. 

I see the annotation toolbox on the left side on rviz. Moreover, I renamed data/example.pcd
 to data/example123.pcd to check, whether the launchfile notices the change by throwing an error. It does, so I can conclude that the example.pcd file is read and the "find rviz_cloud_annotation" in roslaunch file does work.

Some additional information:
ROS-version = Kinetic (Kame), 
OS = Ubuntu 16.04,

My error message:

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rviz_cloud_annotation_node/annotation_cloud: /home/Gabrielm/cat...
 * /rviz_cloud_annotation_node/annotation_read_filename: /home/Gabrielm/cat...
 * /rviz_cloud_annotation_node/annotation_write_filename: /home/Gabrielm/cat...
 * /rviz_cloud_annotation_node/cloud_filename: /home/Gabrielm/cat...
 * /rviz_cloud_annotation_node/color_importance: 1.0
 * /rviz_cloud_annotation_node/label_names_filename: /home/Gabrielm/cat...
 * /rviz_cloud_annotation_node/label_size: 0.002
 * /rviz_cloud_annotation_node/neigh_search_params: 10
 * /rviz_cloud_annotation_node/neigh_search_type: 2
 * /rviz_cloud_annotation_node/normal_importance: 0.5
 * /rviz_cloud_annotation_node/position_importance: 0.1
 * /rviz_cloud_annotation_node/show_zero_weight_control_points: False
 * /rviz_cloud_annotation_node/update_topic: /point_cloud

NODES
  /
    annotation_rviz (rviz/rviz)
    rviz_cloud_annotation_node (rviz_cloud_annotation/rviz_cloud_annotation_node)

ROS_MASTER_URI=http://localhost:11311

process[rviz_cloud_annotation_node-1]: started with pid [19189]
process[annotation_rviz-2]: started with pid [19190]
Failed to find match for field 'curvature'.
[ INFO] [1573803973.838675325]: rviz version 1.12.17
[ INFO] [1573803973.838706167]: compiled against Qt version 5.5.1
[ INFO] [1573803973.838712651]: compiled against OGRE version 1.9.0 (Ghadamon)
[rviz_cloud_annotation_node-1] process has died [pid 19189, exit code -11, cmd /home/Gabrielm/catkin_ws/devel/lib/rviz_cloud_annotation/rviz_cloud_annotation_node __name:=rviz_cloud_annotation_node __log:=/home/Gabrielm/.ros/log/fec26bd2-0776-11ea-8787-58a023283ceb/rviz_cloud_annotation_node-1.log].
log file: /home/Gabrielm/.ros/log/fec26bd2-0776-11ea-8787-58a023283ceb/rviz_cloud_annotation_node-1*.log
[ INFO] [1573803974.432146977]: Stereo is NOT SUPPORTED
[ INFO] [1573803974.432196482]: OpenGl version: 4.6 (GLSL 4.6).

**Comment by Marcel-Gabriel-bertrandt** [comment]
I found a solution just a few minutes ago. Anyway, I wanted to share this issue, as it may help others with the same problems...

The solution is following:

You have to install pointcloudlib via sudo apt-get command:
$sudo apt-get update
$sudo apt-get install ros-kinetic-pcl-conversions
$sudo apt-get install ros-kinetic-pcl-ros
(see https://answers.ros.org/question/235891/how-to-remove-this-error-in-pcl/ for more info)

AND install the library from source. I already installed it, but the version I installed from source did not match the version that is installed via apt-get.

At the current state, pcl version 1.7 is installed via apt-get.
I downloaded pcl 1.7.2 (https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.7.2) 
, made it with cmake (mkdir build; cd build; cmake ..) and installed it afterwards (sudo make install).

Then I deleted my catkin build folder, build my project with catkin_make et voilá! It works.

**Comment by houhaol** [comment]
> I found a solution just a few minutes ago. Anyway, I wanted to share this issue, as it may help others with the same problems...
> 
> The solution is following:
> 
> You have to install pointcloudlib via sudo apt-get command:
> $sudo apt-get update
> $sudo apt-get install ros-kinetic-pcl-conversions
> $sudo apt-get install ros-kinetic-pcl-ros
> (see https://answers.ros.org/question/235891/how-to-remove-this-error-in-pcl/ for more info)
> 
> AND install the library from source. I already installed it, but the version I installed from source did not match the version that is installed via apt-get.
> 
> At the current state, pcl version 1.7 is installed via apt-get.
> I downloaded pcl 1.7.2 (https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.7.2)
> , made it with cmake (mkdir build; cd build; cmake ..) and installed it afterwards (sudo make install).
> 
> Then I deleted my catkin build folder, build my project with catkin_make et voilá! It works.

Thanks for your sharing. I met the same issue. So it means only PCL-1.7 version is compatible, right? Just make sure you removed the previous pcl version and installed 1.7 instead to solve it. Thx.

**Comment by Marcel-Gabriel-bertrandt** [comment]
You are welcome ;)

I also tried pcl version 1.8 (build with cmake), but this did not seem to work. As I said, the version installed via apt-get and the one you build with cmake should match. I don't know how to install pc 1.8 with apt-get, so I recommend to keep using 1.7.

**Comment by houhaol** [comment]
> You are welcome ;)
> 
> I also tried pcl version 1.8 (build with cmake), but this did not seem to work. As I said, the version installed via apt-get and the one you build with cmake should match. I don't know how to install pc 1.8 with apt-get, so I recommend to keep using 1.7.

Thanks for your reply. Mine is PCL 1.10 and the point cloud can't show up either. Now i have to install pc1.7 to let it work. :(
Btw, do you know any other tools for this point cloud annotation task? I'm still exploring that. Really appreciate your sharing.
