### ISSUE TITLE
Labeling of sparse point clouds

### ISSUE THREAD

**Issue by Gitanjali450** [RMonica/rviz_cloud_annotation#9]
Hello,
Thank you very much for the tool.
The points clouds which I want to label with this tool are too sparse, so that 'setting the control points' method would not work efficiently. Is there a way to change some parameters within this tool, so that a larger distance between the neighbouring points can be accounted for and I could label efficiently using the control points method. If so, which parameter do I need to change and to what value do I need to set it to?
Thank you.

**Comment by RMonica** [comment]
Did you try increasing the `max_label_distance` parameter from the default value?
The default should be 0.1, I think.

**Comment by Gitanjali450** [comment]
Where can I find the parameter 'max_label_distance'? Or do you mean the 'position_importance' parameter in the example.launch file?

**Comment by RMonica** [comment]
If a parameter is not in the launch file, you can add it:
```
<param name="max_label_distance" type="double" value="0.1" />
```

Parameters and default values are listed in `src/rviz_cloud_annotation.h`.
Also, many parameters are listed in the README.

**Comment by Gitanjali450** [comment]
Thank you. It works much better!
